/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import ClaseDocumentos.CSV;
import Entidades.*;
import java.awt.HeadlessException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nestor
 */
public class RegistroPro extends javax.swing.JFrame {
         DefaultTableModel  modeloreg;
         int id=0;
    /**
     * Creates new form RegistroPro
     */
    public RegistroPro() {
        initComponents();
        modeloreg= (DefaultTableModel)this.jtReg.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNprducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SPcantidad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtCostoP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtReg = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAñadir = new javax.swing.JButton();
        btnCancelarREg = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        btnElimminar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Añadir Productos");

        jLabel2.setText("Nombre del Producto:");

        jLabel3.setText("Cantidad en existencia:");

        SPcantidad.setModel(new javax.swing.SpinnerNumberModel(5, 1, 5000, 1));

        jLabel4.setText("Costo producto");

        jLabel5.setText("Precio de Venta");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Lista de productos añadidos");

        jtReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_producto", "Producto", "Cantidad", "Costo", "Precio"
            }
        ));
        jScrollPane2.setViewportView(jtReg);

        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventario.png"))); // NOI18N
        btnAñadir.setText("Añadir al inventario");
        btnAñadir.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnCancelarREg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/270-cancel-circle.png"))); // NOI18N
        btnCancelarREg.setText("  Cancelar");
        btnCancelarREg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarREgActionPerformed(evt);
            }
        });

        btnTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/036-profile.png"))); // NOI18N
        btnTerminar.setText("   Terminar registro");
        btnTerminar.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        btnElimminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/173-bin.png"))); // NOI18N
        btnElimminar.setText("Eliminar seleccionado");
        btnElimminar.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnElimminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTerminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnElimminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarREg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnAñadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnElimminar)
                .addGap(15, 15, 15)
                .addComponent(btnTerminar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarREg)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(51, 51, 51)
                        .addComponent(SPcantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNprducto)
                            .addComponent(txtCostoP)
                            .addComponent(txtPrecioV, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNprducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(SPcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCostoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrecioV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        try{
            if (txtPrecioV.getText().equals("") || txtCostoP.getText().equals("")|| txtNprducto.getText().equals("")) {
                
                Icon icono= new ImageIcon("src\\imagenes\\iconE.png");
                JOptionPane.showMessageDialog(rootPane,"No se puede dejar ningun campo vacio","CAMPOS VACIOS",JOptionPane.PLAIN_MESSAGE,icono);
            }
            else{
      
                String[] tabla = {String.valueOf(id),txtNprducto.getText(),SPcantidad.getValue().toString()
                                    ,txtCostoP.getText(),txtPrecioV.getText()};
                modeloreg.addRow(tabla);
                jtReg.setModel(modeloreg);

                SPcantidad.setValue(5);
                txtNprducto.setText("");
                txtCostoP.setText("");
                txtPrecioV.setText("");
                id+=1;
                }
        }
        catch (HeadlessException e)
        {
            Icon icono= new ImageIcon("src\\imagenes\\iconE.png");
             JOptionPane.showMessageDialog(rootPane,e,"",JOptionPane.PLAIN_MESSAGE,icono);
                
        }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        for(int i=0; i<1; i++)
        {
            
               Inicio.lInv=new ArrayList<>();
            for(int j=0; j<jtReg.getRowCount(); j++)
            {
                int idProducto=Integer.parseInt((String)jtReg.getValueAt(j, 0).toString());
                String NProducto=jtReg.getValueAt(j, 1).toString();
                int cantidad=Integer.parseInt((String)jtReg.getValueAt(j, 2));
                double costo=Double.parseDouble((String)jtReg.getValueAt(j, 3));
                double precio=Double.parseDouble((String)jtReg.getValueAt(j, 4));
                
                Inicio.lInv.add(new Inventario(idProducto,NProducto,cantidad,costo,precio));
            }
        }
        CSV c= new CSV();
             try {
                 c.Crear();
             } catch (IOException ex) {
                 Logger.getLogger(RegistroPro.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnCancelarREgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarREgActionPerformed
      modeloreg.getDataVector().removeAllElements();
      txtCostoP.setText("");
      txtPrecioV.setText("");
      txtNprducto.setText("");
      
    }//GEN-LAST:event_btnCancelarREgActionPerformed

    private void btnElimminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimminarActionPerformed
        // TODO add your handling code here:
        try {
        int fila = jtReg.getSelectedRow();
        if (fila >= 0) {
            modeloreg.removeRow(fila);
        }
        }catch(Exception e)
        {
            Icon icono= new ImageIcon("src\\imagenes\\iconE.png");
             JOptionPane.showMessageDialog(rootPane,"Seleccione una fila","Error",JOptionPane.PLAIN_MESSAGE,icono);
              
        }
    }//GEN-LAST:event_btnElimminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SPcantidad;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelarREg;
    private javax.swing.JButton btnElimminar;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtReg;
    private javax.swing.JTextField txtCostoP;
    private javax.swing.JTextField txtNprducto;
    private javax.swing.JTextField txtPrecioV;
    // End of variables declaration//GEN-END:variables
}
