/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import ClaseDocumentos.*;
import Entidades.*;
import java.awt.HeadlessException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nestor
 * Iconos diseñados por https://www.flaticon.es/autores/freepik 
 * pagina: https://www.flaticon.es/
 */
public class Venta extends javax.swing.JFrame {
        public ArrayList<Cliente> lClie;
        double total=0;
        DefaultTableModel modeloventa;
        DefaultTableModel modeloinventario;
        DefaultTableModel modeloclientes;
        DefaultTableModel modelopedidos;
        int per;
            
    public Venta() {
        initComponents();
        lClie=new ArrayList<>();
        modeloventa = (DefaultTableModel)jtDetalleComp.getModel();
        modeloinventario= (DefaultTableModel)jtInventario.getModel();
        modeloclientes= (DefaultTableModel)jtListaClientes.getModel();
        modelopedidos= (DefaultTableModel)jtListaProductos.getModel();
        cargaraProductos();
    }
    
    class funcion implements Funciones
     {

        @Override
        public double SubTotal(int Cantidad, double precio)
        {
            double sub= Cantidad*precio;
             return sub;
        }

        @Override
        public double Total( double subt, double TT)
        {
           TT+=subt;
           return TT;
        }

        @Override
        public double iva(double precio) 
        {
            return precio*0.13;
        }
            
     }
    
            private void cargaraProductos()
            {
              
                if (Inicio.lInv.isEmpty()) 
                {
                     Icon icono= new ImageIcon("src\\imagenes\\iconE.png");
                     JOptionPane.showMessageDialog(rootPane,"No hay productos que cargar","Lista Vacia",JOptionPane.PLAIN_MESSAGE,icono);
                
                }else{
                     this.CbProducto.removeAllItems();
                for (int i = 0; i < Inicio.lInv.size(); i++) 
                
                {
                    this.CbProducto.addItem(Inicio.lInv.get(i).getProducName());
                }
                }
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CbProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Spcantidad = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDetalleComp = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDUI = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnAñadirP = new javax.swing.JButton();
        btnCancelarP = new javax.swing.JButton();
        btnTerminarCom = new javax.swing.JButton();
        btnMostrarTotal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtListaClientes = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtListaProductos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnMr = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPV = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtInventario = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnGCambios = new javax.swing.JButton();
        btnAñadiralReg = new javax.swing.JButton();
        btnGuardarDatos = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtcantidad = new javax.swing.JTextField();

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel1.setText("Nombre Cliente");

        jLabel2.setText("Producto: ");

        CbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto 1", "Producto 2", "Producto 3" }));

        jLabel3.setText("Cantidad");

        Spcantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        jtDetalleComp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Producto", "Producto", "Cantidad", "Precio", "Sub-total"
            }
        ));
        jScrollPane1.setViewportView(jtDetalleComp);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Total    $");

        lbTotal.setText("             ");

        jLabel6.setText("DUI");

        btnAñadirP.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnAñadirP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/059-cart.png"))); // NOI18N
        btnAñadirP.setText("  Añadir Producto");
        btnAñadirP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAñadirP.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnAñadirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirPActionPerformed(evt);
            }
        });

        btnCancelarP.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnCancelarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/270-cancel-circle.png"))); // NOI18N
        btnCancelarP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelarP.setLabel(" Cancelar Compra");
        btnCancelarP.setMargin(new java.awt.Insets(2, 6, 2, 6));
        btnCancelarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPActionPerformed(evt);
            }
        });

        btnTerminarCom.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnTerminarCom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/060-coin-dollar.png"))); // NOI18N
        btnTerminarCom.setText("Terminar Compra");
        btnTerminarCom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTerminarCom.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnTerminarCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarComActionPerformed(evt);
            }
        });

        btnMostrarTotal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnMostrarTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/065-calculator.png"))); // NOI18N
        btnMostrarTotal.setText("  Mostrar Total");
        btnMostrarTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMostrarTotal.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnMostrarTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAñadirP, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(btnCancelarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTerminarCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnAñadirP)
                .addGap(11, 11, 11)
                .addComponent(btnCancelarP)
                .addGap(11, 11, 11)
                .addComponent(btnMostrarTotal)
                .addGap(11, 11, 11)
                .addComponent(btnTerminarCom)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Spcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDUI)
                                .addComponent(CbProducto, 0, 122, Short.MAX_VALUE))
                            .addComponent(txtNCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Spcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Venta", jPanel1);

        jtListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Cliente", "Nombre", "DUI", "Fecha", "Total"
            }
        ));
        jtListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtListaClientes);
        if (jtListaClientes.getColumnModel().getColumnCount() > 0) {
            jtListaClientes.getColumnModel().getColumn(0).setMinWidth(50);
            jtListaClientes.getColumnModel().getColumn(0).setPreferredWidth(80);
            jtListaClientes.getColumnModel().getColumn(0).setMaxWidth(80);
            jtListaClientes.getColumnModel().getColumn(1).setMinWidth(100);
            jtListaClientes.getColumnModel().getColumn(1).setPreferredWidth(120);
            jtListaClientes.getColumnModel().getColumn(1).setMaxWidth(140);
            jtListaClientes.getColumnModel().getColumn(2).setMinWidth(50);
            jtListaClientes.getColumnModel().getColumn(2).setPreferredWidth(60);
            jtListaClientes.getColumnModel().getColumn(2).setMaxWidth(70);
            jtListaClientes.getColumnModel().getColumn(3).setMinWidth(90);
            jtListaClientes.getColumnModel().getColumn(3).setPreferredWidth(100);
            jtListaClientes.getColumnModel().getColumn(3).setMaxWidth(130);
            jtListaClientes.getColumnModel().getColumn(4).setMinWidth(50);
            jtListaClientes.getColumnModel().getColumn(4).setPreferredWidth(60);
            jtListaClientes.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        jtListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Producto", "Producto", "Cantidad", "Precio", "Sub-Total"
            }
        ));
        jScrollPane3.setViewportView(jtListaProductos);
        if (jtListaProductos.getColumnModel().getColumnCount() > 0) {
            jtListaProductos.getColumnModel().getColumn(0).setMinWidth(65);
            jtListaProductos.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtListaProductos.getColumnModel().getColumn(0).setMaxWidth(80);
            jtListaProductos.getColumnModel().getColumn(1).setMinWidth(90);
            jtListaProductos.getColumnModel().getColumn(1).setPreferredWidth(130);
            jtListaProductos.getColumnModel().getColumn(1).setMaxWidth(130);
            jtListaProductos.getColumnModel().getColumn(2).setMinWidth(60);
            jtListaProductos.getColumnModel().getColumn(2).setPreferredWidth(70);
            jtListaProductos.getColumnModel().getColumn(2).setMaxWidth(70);
            jtListaProductos.getColumnModel().getColumn(3).setMinWidth(60);
            jtListaProductos.getColumnModel().getColumn(3).setPreferredWidth(80);
            jtListaProductos.getColumnModel().getColumn(3).setMaxWidth(80);
            jtListaProductos.getColumnModel().getColumn(4).setMinWidth(60);
            jtListaProductos.getColumnModel().getColumn(4).setPreferredWidth(80);
            jtListaProductos.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Registro de ventas ");

        btnMr.setText("Mostrar Registro");
        btnMr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMrActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/480-file-pdf.png"))); // NOI18N
        jButton1.setText("Guardar Registros");
        jButton1.setMargin(new java.awt.Insets(2, 6, 2, 8));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/480-file-pdf.png"))); // NOI18N
        jButton2.setText("   Ver un Registro");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(38, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMr)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                                .addComponent(jScrollPane3)))))
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMr)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Registros", jPanel2);

        jLabel7.setText("Nombre del Producto:");

        jLabel8.setText("Cantidad en existencia:");

        jLabel9.setText("Costo producto");

        jLabel10.setText("Precio de Venta");

        jtInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_producto", "Producto", "Cantidad", "Costo", "Precio"
            }
        ));
        jtInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtInventarioMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtInventario);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Detalle de Inventario");

        jLabel13.setText("ID de Producto");

        btnGCambios.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnGCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventario.png"))); // NOI18N
        btnGCambios.setText("Guardar Cambios");
        btnGCambios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGCambios.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnGCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGCambiosActionPerformed(evt);
            }
        });

        btnAñadiralReg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnAñadiralReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/036-profile.png"))); // NOI18N
        btnAñadiralReg.setText("Añadir al Registro");
        btnAñadiralReg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAñadiralReg.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnAñadiralReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadiralRegActionPerformed(evt);
            }
        });

        btnGuardarDatos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnGuardarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/101-database.png"))); // NOI18N
        btnGuardarDatos.setText(" Guardar Datos");
        btnGuardarDatos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGuardarDatos.setMargin(new java.awt.Insets(2, 8, 2, 14));
        btnGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDatosActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/270-cancel-circle.png"))); // NOI18N
        btnCancelar.setText("  Cancelar");
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.setMargin(new java.awt.Insets(2, 8, 2, 14));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/173-bin.png"))); // NOI18N
        btnEliminar.setText("Eliminar Producto");
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminar.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAñadiralReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnGCambios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAñadiralReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPV, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtCosto, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtID)
                            .addComponent(txtcantidad))
                        .addGap(65, 65, 65)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Inventario", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      //boton cancelar solo limpia el conetido ingresado y cargado
        
       modeloinventario.getDataVector().removeAllElements();
       txtCosto.setText("");
       txtPV.setText("");
       txtProducto.setText("");
       txtID.setText("");
       txtcantidad.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAñadirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirPActionPerformed
      
       
        try{
           
            String prod;
            int cantidad;
            double precio;
            int cont=-1;
            Boolean recorrer=true;
            prod=CbProducto.getSelectedItem().toString();
                while(recorrer)
                {
                    cont++;
                    if (Inicio.lInv.get(cont).getProducName().equals(prod)) recorrer=false;
                }
                    int id=Inicio.lInv.get(cont).getIdprod();
                    funcion f = new funcion();
                    precio=Inicio.lInv.get(cont).getPrecioVenta();
                    if ((int)Spcantidad.getValue()>Inicio.lInv.get(cont).getExistencias()) {
                        Icon icono= new ImageIcon("src\\imagenes\\iconE.png");
                        JOptionPane.showMessageDialog(rootPane,"No hay cantidad suficiente de este producto \n"
                                                      +"total existencia: "+String.valueOf(Inicio.lInv.get(cont).getExistencias())
                                                      ,"",JOptionPane.PLAIN_MESSAGE,icono);
                        cantidad=Inicio.lInv.get(cont).getExistencias();
                     }else 
                            {
                                cantidad= (int) Spcantidad.getValue();
                            }
                    double subtotal= f.SubTotal(cantidad, precio);
                    String subTotal= String.valueOf(subtotal);
                    total=f.Total(subtotal,total);


                    String[] tabla = {String.valueOf(id),CbProducto.getSelectedItem().toString(),Spcantidad.getValue().toString(),String.valueOf(precio),subTotal};
                    modeloventa.addRow(tabla);
                    jtDetalleComp.setModel(modeloventa);

                    Spcantidad.setValue(1);
                    id+=1;
        }
        catch (HeadlessException e)
        {
            Icon icono= new ImageIcon("src\\imagenes\\iconE.png");
             JOptionPane.showMessageDialog(rootPane,"No puede dejar ningun campo vacio","",JOptionPane.PLAIN_MESSAGE,icono);
                
        }
    }//GEN-LAST:event_btnAñadirPActionPerformed

    private void btnAñadiralRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadiralRegActionPerformed
        //boton que agrega los datos a la tabla 
         try{
            if (txtPV.getText().equals("") || txtCosto.getText().equals("")|| txtProducto.getText().equals("") || txtID.getText().equals("")) {
                
                Icon icono= new ImageIcon("src\\imagenes\\iconE.png");
                JOptionPane.showMessageDialog(rootPane,"No se puede dejar ningun campo vacio","CAMPOS VACIOS",JOptionPane.PLAIN_MESSAGE,icono);
            }
            else{
                for (int i = 0; i < Inicio.lInv.size(); i++) 
                {
                    if (txtID.getText().equals(Inicio.lInv.get(i).getIdprod())) 
                    {
                        //Falta mostrar el  mensaje que ya esta es id
                        Icon icono= new ImageIcon("src\\imagenes\\iconE.png");
                        JOptionPane.showMessageDialog(rootPane,"El ID ingresado ya existe, ingrese otro","ID erroneo",JOptionPane.PLAIN_MESSAGE,icono);
                        String idn;
                        idn= JOptionPane.showInputDialog("Ingrese el nuevo ID");
                        txtID.setText(idn);
                        
                    }
                }
                
                String[] tabla = {txtID.getText(),txtProducto.getText(),txtcantidad.getText()
                                    ,txtCosto.getText(),txtPV.getText()};
                modeloinventario.addRow(tabla);
                jtInventario.setModel(modeloinventario);

               txtcantidad.setText("");
                txtProducto.setText("");
                txtCosto.setText("");
                txtPV.setText("");
                txtID.setText("");
                }
        }
        catch (HeadlessException e)
        {
            Icon icono= new ImageIcon("src\\imagenes\\iconE.png");
             JOptionPane.showMessageDialog(rootPane,e,"",JOptionPane.PLAIN_MESSAGE,icono);
                
        }
    }//GEN-LAST:event_btnAñadiralRegActionPerformed

    private void jtInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtInventarioMouseClicked
       
         int Indice= this.jtInventario.getSelectedRow();
         DefaultTableModel mdlTmp=(DefaultTableModel)this.jtInventario.getModel();
         this.txtID.setText(mdlTmp.getValueAt(Indice, 0).toString().trim());
         this.txtProducto.setText(mdlTmp.getValueAt(Indice, 1).toString().trim());
         this.txtcantidad.setText(mdlTmp.getValueAt(Indice, 2).toString().trim()); 
         this.txtCosto.setText(mdlTmp.getValueAt(Indice, 3).toString().trim());
         this.txtPV.setText(mdlTmp.getValueAt(Indice, 4).toString().trim());
       
    }//GEN-LAST:event_jtInventarioMouseClicked

    private void btnGCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGCambiosActionPerformed
      //boton que guarda los cambios de los datos modificados en la tabla y en la lista
      
             Icon icono= new ImageIcon("src\\imagenes\\iconE.png");
             JOptionPane.showMessageDialog(rootPane,"Seleccione el archivo que fue cargado o creado \n "
                                                    +"Para guardar los datos cambiados"
                                                   ,"Guardar Datos",JOptionPane.PLAIN_MESSAGE,icono);
                
           int Indice= this.jtInventario.getSelectedRow();
     
           jtInventario.setValueAt(txtID.getText(), Indice, 0);
           jtInventario.setValueAt(txtProducto.getText(), Indice, 1);
           jtInventario.setValueAt(txtcantidad.getText(), Indice, 2);
           jtInventario.setValueAt(txtCosto.getText(), Indice, 3);
           jtInventario.setValueAt(txtPV.getText(), Indice, 4);
          
                int idProducto=Integer.parseInt((String)jtInventario.getValueAt(Indice, 0).toString());
                String NProducto=jtInventario.getValueAt(Indice, 1).toString();
                int cantidad=Integer.parseInt((String)jtInventario.getValueAt(Indice, 2));
                double costo=Double.parseDouble((String)jtInventario.getValueAt(Indice, 3));
                double precio=Double.parseDouble((String)jtInventario.getValueAt(Indice, 4));
              
                Inicio.lInv.get(Indice).setIdprod(idProducto);
                Inicio.lInv.get(Indice).setProducName(NProducto);
                Inicio.lInv.get(Indice).setExistencias(cantidad);
                Inicio.lInv.get(Indice).setCostoProd(costo);
                Inicio.lInv.get(Indice).setPrecioVenta(precio);
               
            
                        
      
//        for(int i=0; i<1; i++)
//        {
//            
//               Inicio.lInv=new ArrayList<>();
//            for(int j=0; j<jtInventario.getRowCount(); j++)
//            {
//                int idProducto=Integer.parseInt((String)jtInventario.getValueAt(j, 0).toString());
//                String NProducto=jtInventario.getValueAt(j, 1).toString();
//                int cantidad=Integer.parseInt((String)jtInventario.getValueAt(j, 2));
//                double costo=Double.parseDouble((String)jtInventario.getValueAt(j, 3));
//                double precio=Double.parseDouble((String)jtInventario.getValueAt(j, 4));
//                
//                Inicio.lInv.add(new Inventario(idProducto,NProducto,cantidad,costo,precio));
//            }
//        }
       
    }//GEN-LAST:event_btnGCambiosActionPerformed

    private void btnGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDatosActionPerformed
       //boton que agrega los datos al archivo CSV modificados o con nuevos datos
       int añadidos=0;
       añadidos = jtInventario.getRowCount()-Inicio.lInv.size();
        if (añadidos!=0) {
            
            for (int j = Inicio.lInv.size(); j <jtInventario.getRowCount(); j++) 
            {
                 int idProducto=Integer.parseInt((String)jtInventario.getValueAt(j, 0).toString());
                String NProducto=jtInventario.getValueAt(j, 1).toString();
                int cantidad=Integer.parseInt((String)jtInventario.getValueAt(j, 2));
                double costo=Double.parseDouble((String)jtInventario.getValueAt(j, 3));
                double precio=Double.parseDouble((String)jtInventario.getValueAt(j, 4));
                
                Inicio.lInv.add(new Inventario(idProducto,NProducto,cantidad,costo,precio));
            
        }
        }
        CSV c= new CSV();
               
            try {
                c.Modificar();
            } catch (IOException ex) {
                Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
            }
              
    }//GEN-LAST:event_btnGuardarDatosActionPerformed

        @SuppressWarnings("empty-statement")
    private void btnTerminarComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarComActionPerformed
        // Boton que termina la compra añadiendo a la lista clientes y a la lista producto
        Date fecha= new Date();
        if (lClie.isEmpty()) 
        {
            per=0;
        }else
            {
                per=lClie.size();
            }
        for (int i = 0; i < 1; i++) 
        {
            lClie.add(new Cliente(String.valueOf("0"+per), txtNCliente.getText(), txtDUI.getText(), fecha, total));
            lClie.get(per).lPedido= new ArrayList<>();
            for (int j = 0; j < jtDetalleComp.getRowCount(); j++) 
            
            {
                  String prod;
                  int cont=-1;
                  Boolean recorrer=true;
                  prod=jtDetalleComp.getValueAt(j, 1).toString();
                while(recorrer)
                {
                    cont++;
                    if (Inicio.lInv.get(cont).getProducName().equals(prod)) recorrer=false;
                }
              
                String idProd=jtDetalleComp.getValueAt(j, 0).toString();
                String Producto=jtDetalleComp.getValueAt(j, 1).toString();
                int cantidad=Integer.parseInt((String)jtDetalleComp.getValueAt(j, 2));
                double precio=Double.parseDouble((String)jtDetalleComp.getValueAt(j, 3));
                double subtotal=Double.parseDouble((String)jtDetalleComp.getValueAt(j, 4));
                int existencia=Inicio.lInv.get(cont).getExistencias()-cantidad;
                Inicio.lInv.get(cont).setExistencias(existencia);
                lClie.get(per).lPedido.add(new Producto(idProd,Producto,cantidad,precio,subtotal));
            }
        }
        total=0;
        modeloventa.getDataVector().removeAllElements();
        txtNCliente.setText("");
        txtDUI.setText("");
        Spcantidad.setValue(1);
        
    }//GEN-LAST:event_btnTerminarComActionPerformed

    private void btnMostrarTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTotalActionPerformed
       //Ingresa el total al label
       lbTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnMostrarTotalActionPerformed

    private void btnCancelarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPActionPerformed
       txtNCliente.setText("");
       txtDUI.setText("");
       Spcantidad.setValue(1);
       modeloventa.getDataVector().removeAllElements();
    }//GEN-LAST:event_btnCancelarPActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // Evento que carga la lista inventario en la tabla de inventario y la tabla de registros
         modeloinventario.getDataVector().removeAllElements();
         modeloclientes.getDataVector().removeAllElements();
         modelopedidos.getDataVector().removeAllElements();
         try{
        if(Inicio.lInv.isEmpty())
        {
            Icon icono= new ImageIcon(getClass().getResource("src\\imagenes\\iconE.png"));
            JOptionPane.showMessageDialog(rootPane,"No hay datos que mostrar","",JOptionPane.PLAIN_MESSAGE,icono);
        }
        else
        {
            for(int i=0; i<Inicio.lInv.size(); i++)
            {
                
                String[] registroC = {
                          String.valueOf(Inicio.lInv.get(i).getIdprod()),
                         Inicio.lInv.get(i).getProducName(),
                         String.valueOf(Inicio.lInv.get(i).getExistencias()),
                         String.valueOf(Inicio.lInv.get(i).getCostoProd()),
                         String.valueOf(Inicio.lInv.get(i).getPrecioVenta())};
                modeloinventario.addRow(registroC);
            }
            jtInventario.setModel(modeloinventario);
        }
        
        
      
         }catch(HeadlessException e){}
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Boton que elimina un producto de la lista 
                 String idn;
                 idn= JOptionPane.showInputDialog("Ingrese el ID del producto a eliminar");
                 Inicio.lInv.remove(Integer.parseInt(idn));
                 
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMrActionPerformed
        // TODO add your handling code here:
          //codigo para cargar las tablas de registro
          try{
        if(lClie.isEmpty())
        {
            Icon icono= new ImageIcon(getClass().getResource("src\\imagenes\\iconE.png"));
            JOptionPane.showMessageDialog(rootPane,"No hay datos que mostrar","",JOptionPane.PLAIN_MESSAGE,icono);
        }else 
            
            for(int i=0; i<lClie.size(); i++)
            {
                
                String[] registroC = {
                         this.lClie.get(i).getID(),
                         this.lClie.get(i).getNombre(),
                         this.lClie.get(i).getDUI(),
                         String.valueOf( this.lClie.get(i).getFecha()),
                         String.valueOf( this.lClie.get(i).getTotal())
                         };
                modeloclientes.addRow(registroC);
            }
           jtListaClientes.setModel(modeloclientes);
          }catch(HeadlessException e){}
    }//GEN-LAST:event_btnMrActionPerformed

    private void jtListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListaClientesMouseClicked
      //muestra la lista de productos 
       modelopedidos.getDataVector().removeAllElements();

        int indiceCliente=this.jtListaClientes.getSelectedRow();
        int cantPedidos= this.lClie.get(indiceCliente).lPedido.size();
       
        for(int j=0; j<cantPedidos; j++)
        {
            String[] registroP = {this.lClie.get(indiceCliente).lPedido.get(j).id,
                this.lClie.get(indiceCliente).lPedido.get(j).produc,
                Integer.toString(this.lClie.get(indiceCliente).lPedido.get(j).cantidad),
                Double.toString(this.lClie.get(indiceCliente).lPedido.get(j).precio),
                Double.toString(this.lClie.get(indiceCliente).lPedido.get(j).subtotal)};
            modelopedidos.addRow(registroP);
        }
    }//GEN-LAST:event_jtListaClientesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       PDF p = new PDF();
       p.Crear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       PDF p = new PDF();
       p.Abrir();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Venta().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbProducto;
    private javax.swing.JSpinner Spcantidad;
    private javax.swing.JButton btnAñadirP;
    private javax.swing.JButton btnAñadiralReg;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarP;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGCambios;
    private javax.swing.JButton btnGuardarDatos;
    private javax.swing.JButton btnMostrarTotal;
    private javax.swing.JButton btnMr;
    private javax.swing.JButton btnTerminarCom;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtDetalleComp;
    public javax.swing.JTable jtInventario;
    private javax.swing.JTable jtListaClientes;
    private javax.swing.JTable jtListaProductos;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDUI;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNCliente;
    private javax.swing.JTextField txtPV;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtcantidad;
    // End of variables declaration//GEN-END:variables
}
